FROM python:3.12-alpine3.20
WORKDIR /home/plakplaats

# Install build dependencies
RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

# Install UV
COPY --from=ghcr.io/astral-sh/uv:0.6.3 /uv /uvx /bin/
RUN apk add --no-cache --virtual .build-deps python3~=3.12

# Remove previously installed build dependencies, they are not needed anymore
RUN apk del .build-deps

# Cache the python dependencies
COPY uv.lock pyproject.toml ./
RUN uv sync

# Copy the source code
COPY static templates .env server.py ./


ARG STICKER_MAP_PORT
EXPOSE $STICKER_MAP_PORT
CMD ["uv", "run" "python", "server.py"]
