services:
  website:
    build:
      dockerfile: Dockerfile.website
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plakplaats-db
    ports:
      - "5432:5432"