FROM ghcr.io/astral-sh/uv:bookworm
WORKDIR /home/plakplaats

# Install build dependencies
# RUN apk add --no-cache postgresql-libs
# RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

# # Remove previously installed build dependencies, they are not needed anymore
# RUN apk del .build-deps

# Cache the python dependencies
# RUN uv python install
COPY uv.lock pyproject.toml ./
RUN uv sync

# Copy the source code
COPY static templates .env server.py ./


ARG STICKER_MAP_PORT
EXPOSE $STICKER_MAP_PORT
CMD ["uv", "run", "server.py"]
