"""initial schema

Revision ID: 0f3eab76b509
Revises: 
Create Date: 2026-03-10 00:51:28.419836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3eab76b509'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sub'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_sub'), 'admins', ['sub'], unique=True)
    op.create_table('stickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('sub', sa.Integer(), nullable=False),
    sa.Column('posttime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('spots', sa.Integer(), nullable=False),
    sa.Column('boardyear', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sub'], ['users.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stickers_sub'), 'stickers', ['sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stickers_sub'), table_name='stickers')
    op.drop_table('stickers')
    op.drop_index(op.f('ix_admins_sub'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
