"""Add cascade deletes to user relations

Revision ID: 483ac71f7dd6
Revises: de58a26a4e94
Create Date: 2026-03-16 22:09:46.183245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483ac71f7dd6'
down_revision: Union[str, None] = 'de58a26a4e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admins_sub_fkey'), 'admins', type_='foreignkey')
    op.create_foreign_key('admins_sub_fkey', 'admins', 'users', ['sub'], ['sub'], ondelete='CASCADE')
    op.drop_constraint(op.f('stickers_sub_fkey'), 'stickers', type_='foreignkey')
    op.create_foreign_key(None, 'stickers', 'users', ['sub'], ['sub'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stickers', type_='foreignkey')
    op.create_foreign_key(op.f('stickers_sub_fkey'), 'stickers', 'users', ['sub'], ['sub'])
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key(op.f('admins_sub_fkey'), 'admins', 'users', ['sub'], ['sub'])
    # ### end Alembic commands ###
