"""init

Revision ID: 8c0b4ecf9873
Revises: 
Create Date: 2025-04-01 16:47:37.902510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0b4ecf9873'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('logo', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('adderemail', sa.String(), nullable=False),
    sa.Column('posttime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('spots', sa.Integer(), nullable=False),
    sa.Column('boardyear', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stickers')
    op.execute("DROP EXTENSION IF EXISTS postgis CASCASE;")
    # ### end Alembic commands ###
