"""removed logo

Revision ID: 9cef4a5c51e4
Revises: 8c0b4ecf9873
Create Date: 2025-06-16 19:08:24.001953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cef4a5c51e4'
down_revision: Union[str, None] = '8c0b4ecf9873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stickers', 'logo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stickers', sa.Column('logo', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
