"""feat: add reviewed column to sticker table

Revision ID: d96a87949ad4
Revises: 9cef4a5c51e4
Create Date: 2025-11-11 22:46:23.729591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96a87949ad4'
down_revision: Union[str, None] = '9cef4a5c51e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stickers', sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stickers', 'reviewed')
    # ### end Alembic commands ###
