"""simplify admin table

Revision ID: de58a26a4e94
Revises: fdd8e2c7acdd
Create Date: 2026-03-10 16:25:26.454474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de58a26a4e94'
down_revision: Union[str, None] = 'fdd8e2c7acdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_sub'), table_name='admins')
    op.drop_column('admins', 'id')
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_admins_sub'), 'admins', ['sub'], unique=True)
    # ### end Alembic commands ###
